### ISSUE TITLE
去除评论区上面的广告

### ISSUE THREAD

**Issue by wangwei135** [AdlerED/CSDNGreener#1]
为了去除评论区上面的广告, 我自己手动修改了代码

//干掉右侧栏，并让左侧栏填充屏幕
    if (article.test(currentURL)) {
        $("main").css("width", "100%");
        $("aside").remove();
    }

我把上面的代码部分修改为
if (article.test(currentURL)) {
        $("main").css("width", "100%");
        $("aside").remove();
        $("div#dmp_ad_58").remove();  // 去除评论区上面的广告
    }
希望博主能够采纳。
博主写的脚本很好用，我一直在使用。

**Comment by AdlerED** [comment]
非常感谢！已经采纳并修改。
