### ISSUE TITLE
VIP专属文章可以看到吗？ 

### ISSUE THREAD

**Issue by CoderXiaohui** [adlered/CSDNGreener#10]
比如：

> https://blog.csdn.net/qq_43122641/article/details/86507598

**Comment by AdlerED** [comment]
如果有老铁愿意贡献一个VIP的CSDN账号，我可以写个接口把文章读取出来~
此外没有其他办法了:smile:

**Comment by zhangjianliu** [comment]
可以增加个 设置皮肤的功能吗？

**Comment by AdlerED** [comment]
> 可以增加个 设置皮肤的功能吗？

@zhangjianliu 可以详细说说吗，是自定义文章页的皮肤吗？如果是自定义背景的话，很好实现，皮肤的话也可以做
