### ISSUE TITLE
不登录无法复制

### ISSUE THREAD

**Issue by bylucky** [adlered/CSDNGreener#100]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
CSDN越来越垃圾，不登录无法复制，安装了大牛的脚本还是无法复制

**Comment by adlered** [comment]
我这边测试是正常的，请进行以下测试并反馈给我，谢谢：
1. 是否使用Chrome浏览器？
2. 尝试检查脚本更新（点击油猴插件图标-实用工具-用户脚本检查更新）
3. 如进行上述尝试后仍旧无法复制，请留下出现问题网页的URL地址

**Comment by zheng2k16** [comment]
dd 随手写了一个简单的chrome不知是否能撞出火花
