### ISSUE TITLE
能否加一个页面宽度自定义的功能？

### ISSUE THREAD

**Issue by ANGIANAPR** [adlered/CSDNGreener#11]
能否加一个页面宽度自定义（自适应？）的功能？现在的页面感觉有点宽，竖屏（1080X1920）会显示不全，感谢。

**Comment by AdlerED** [comment]
收到啦，这就开始着手，感谢你的建议 :smile:

**Comment by adlered** [comment]
现在宽度可以自动根据你的浏览器窗口大小调整啦，Issue 关闭
