### ISSUE TITLE
右侧导航标题一直上下闪动

### ISSUE THREAD

**Issue by f1ashine** [adlered/CSDNGreener#110]
拖动滚动条后右侧的导航栏一直上下闪动
![capture](https://user-images.githubusercontent.com/26664765/134797207-94e4e9a4-c69b-4dc2-b00c-6816399379c0.gif)

**Comment by f1ashine** [comment]
![Kapture 2021-09-26 at 15 04 47](https://user-images.githubusercontent.com/26664765/134797467-e5eab2cd-c42a-43c8-ae3f-18d9fa5e0d1f.gif)

**Comment by AquariusLyi** [comment]
还没解决嘛 坐标一直来回跳
