### ISSUE TITLE
是否可以自动解锁专栏文章？

### ISSUE THREAD

**Issue by programmerZe** [adlered/CSDNGreener#116]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
该链接的文章需要订阅专栏才能看：https://blog.csdn.net/jacke121/article/details/82495184
希望可以添加免登录就能自动解锁专栏文章的功能
![1](https://user-images.githubusercontent.com/32977308/138581722-d5e3fa7a-f215-4177-a121-50dd9547937a.png)

**Comment by adlered** [comment]
你好，不支持的。
