### ISSUE TITLE
CSDN Tags 广告屏蔽无效

### ISSUE THREAD

**Issue by jamnii** [adlered/CSDNGreener#119]
![image](https://user-images.githubusercontent.com/13510734/139781162-02a02445-39f9-44f1-bd13-242c17721c72.png)

**Comment by twoii** [comment]
参考链接: https://www.csdn.net/tags/OtDaUgzsNDA5NTctYmxvZwO0O0OO0O0O.html

**Comment by adlered** [comment]
问题已收到
