### ISSUE TITLE
建议将作者信息在文章顶部展示

### ISSUE THREAD

**Issue by yexuesong** [AdlerED/CSDNGreener#12]
由于 CSDN 重复类型的文章很多，不像 Stackoverflow 那种问答网站，有着去重机制。所以在多个相似文章中选择「优先」阅读项时，通常是基于作者的相关信息做「快速」判断。

建议将作者信息在文章顶部展示（目前于底部有展示）。

**Comment by AdlerED** [comment]
收到啦，感谢你的建议

**Comment by AdlerED** [comment]
已添加该功能，请更新脚本后体验，如有问题欢迎继续提出 Issue ~
