### ISSUE TITLE
openuserjs.org 无法下载

### ISSUE THREAD

**Issue by DeanShiDirect** [adlered/CSDNGreener#122]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
openuserjs.org/scripts/AdlerED/最强的老牌脚本CSDNGreener：CSDN广告完全过滤、人性化脚本优化

我在这个网站下载 点击install，出现
嗯… 无法访问此页面
页面可能存在问题，或者已永久移动到新的网址。
ERR_INVALID_RESPONSE

**Comment by adlered** [comment]
openuserjs有时连接不稳，最好挂个梯子。
