### ISSUE TITLE
【新特性】未登录可以查看评论

### ISSUE THREAD

**Issue by miaoxu1com** [adlered/CSDNGreener#145]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
问题1：有一些网友的评论对文章的有补充或者扩展，但是现实不登录都无法查看评论，有的时候在公司办公或者不安全的场所，想查看评论，现在CSDN不登录不显示评论带来一些不好体验。

**Comment by miaoxu1com** [comment]
1、希望大大能增加这个特性

**Comment by wang-dua** [comment]
好像没有解决
