### ISSUE TITLE
建议加入日期显示

### ISSUE THREAD

**Issue by cooper1x** [adlered/CSDNGreener#147]
### 请描述你遇到的问题：
![image](https://user-images.githubusercontent.com/9080789/164216155-cd5b3250-b057-42f7-9b94-431d027bf5e4.png)
https://blog.csdn.net/kikikiuu/article/details/122473837
有时候不知道看的文章是哪一年写的，还有没有时效性。

**Comment by zii4914** [comment]
支持，我也很希望加上显示

**Comment by O-kai** [comment]
我也是非常需要看时间，希望作者把时间加上，有些技术文章对时效性还是挺重要的！😁

**Comment by declandragon** [comment]
用户ID，日期，阅读量，建议一起显示，非常感谢

![](https://s3.bmp.ovh/imgs/2022/05/18/0a986e4437cf2872.png)

**Comment by zii4914** [comment]
@cooper1x @declandragon @O-kai @antnesswcm 
可以参考这个，在本地修改一下js脚本先用着。这个改动有人提交了，但是好像被拒绝了。
https://github.com/adlered/CSDNGreener/issues/135#issuecomment-1091191246

**Comment by antnesswcm** [comment]
好的

**Comment by ExcuseLme** [comment]
> @cooper1x @declandragon @O-kai @antnesswcm 可以参考这个，在本地修改一下js脚本先用着。这个改动有人提交了，但是好像被拒绝了。 [#135 (comment)](https://github.com/adlered/CSDNGreener/issues/135#issuecomment-1091191246)

非常感谢
