### ISSUE TITLE
无法复制CSDN代码块

### ISSUE THREAD

**Issue by MSNLPer1** [adlered/CSDNGreener#152]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：

无法复制CSDN代码块

**Comment by bencky1017** [comment]
$('#content_views pre,#content_views pre code').css({'-webkit-user-select':'auto'},{'user-select':':auto'});
加上这一段就可以进行复制代码块

**Comment by bencky1017** [comment]
`$('#content_views pre,#content_views pre code').css({'-webkit-user-select':'auto'},{'user-select':':auto'});`
加上这一段就可以不登录复制代码块了
