### ISSUE TITLE
【bug-report】CSDN顶部栏一直抖动的问题

### ISSUE THREAD

**Issue by cooper1x** [adlered/CSDNGreener#155]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
macOS的Edge浏览器，向上滚动时，这个区域一直上下抖动。
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/9080789/171074576-b03804aa-f540-4495-ac7e-76df016738c2.png">

**Comment by cooper1x** [comment]
![2022-05-31 09-50-56.2022-05-31 09_51_49.gif](https://s2.loli.net/2022/05/31/AeoZLTlsGBw8J9h.gif)

**Comment by adlered** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/6754458/172659827-df67de47-5793-43a8-8d8c-2a885d90456d.png">
您好，我这边macos，下载m1版本的最新版edge测试没有问题，请您检查下是否有其他插件或脚本冲突

**Comment by cooper1x** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/9080789/172791043-c2fdd5db-8543-4e70-96f8-6d4cb671ceff.png">
确实跟其他脚本冲突了，问题解决。
