### ISSUE TITLE
侧边栏没了

### ISSUE THREAD

**Issue by tjx666** [AdlerED/CSDNGreener#16]
![screenshot_2020-02-22_13-09-56](https://user-images.githubusercontent.com/41773861/75086909-a15cc400-5574-11ea-88f8-a1401a8fa79d.png)

**Comment by AdlerED** [comment]
问题已复现，正在排查，感谢！

**Comment by AdlerED** [comment]
问题已紧急修复，请更新后重试！感谢你的反馈
