### ISSUE TITLE
我在csdn页面中阻止了csdn的一个脚本,它会与当前插件冲突,页面会不停抖动

### ISSUE THREAD

**Issue by xjl456852** [adlered/CSDNGreener#160]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
我在csdn中阻止了一个csdn的脚本运行.禁止加载这个脚本.
脚本名:
https://csdnimg.cn/release/blogv2/dist/pc/js/common-a1dfbf1dc3.min.js
这个脚本跟页面上显示的代码行号有关.每个csdn页面我都不想运行这个脚本.
测试页面:
https://blog.csdn.net/stusss/article/details/115626412

但是阻止它运行后,当前的页面会自动上下不停的抖动. 鼠标上下滚动一下,可能会停止滚动, 鼠标再次上下滚动一下,就可能会再次自动滚动. 禁止当前csdn插件后,就不会出现这个问题.

我已经将页面抖动的画面录制图像.放到云盘里了.
非常感谢.
录制视频:
链接: https://pan.baidu.com/s/175FMSXvPSGJchjR4Qlg3iw?pwd=7a4q 提取码: 7a4q

**Comment by adlered** [comment]
您是如何禁止这个脚本加载的？

**Comment by xjl456852** [comment]
> 您是如何禁止这个脚本加载的？

这个使用chrome或者edge自带的阻止某个网络请求的url地址.
例如用chrome来阻止的话.
按快捷键F12,打开开发者模式.
切换到 newwork 标签. F5刷新当前页面, 在一堆请求中,选中一个,鼠标右键->block request url.
这个请求就会被加入到阻止请求列表. 下次再刷新,这个地址将被阻止请求.
![image](https://user-images.githubusercontent.com/8008097/174819030-4c859f19-b072-4093-9d1b-121de904513f.png)


也可以用浏览器插件,ublock origin来添加阻止列表.
