### ISSUE TITLE
CSDN去除左侧广告，把文章目录索引也一并删除了

### ISSUE THREAD

**Issue by Lingoing** [adlered/CSDNGreener#169]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：https://blog.csdn.net/Augenstern_QXL/article/details/117253848
![无标题](https://user-images.githubusercontent.com/35037743/185067907-e2221854-8f2e-46bd-831e-6de01179e243.png)

**Comment by JaydenChang** [comment]
同遇到这个问题，就算在插件设置中勾选显示目录，最后也还是无法显示 (浏览器为edge
