### ISSUE TITLE
免登录复制不可用

### ISSUE THREAD

**Issue by programmerZe** [AdlerED/CSDNGreener#17]
URL：https://blog.csdn.net/Eastmount/article/details/83268410
浏览器：Chrome 80.0.3987.116
![image](https://user-images.githubusercontent.com/32977308/75111875-58dafe80-5679-11ea-8ca9-02af42f8c7ad.png)

**Comment by AdlerED** [comment]
CSDN 在登录后复制可能倾注了全部的开发力量吧 （逃 
还在努力解决~

**Comment by AdlerED** [comment]
问题已修复！你的脚本应该已经自动更新了，试试看吧 :smile:

**Comment by programmerZe** [comment]
非常感谢！
