### ISSUE TITLE
使用csdn会 弹窗要求登录

### ISSUE THREAD

**Issue by admincopm** [adlered/CSDNGreener#197]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
使用csdn会 弹窗要求登录

**Comment by knowanegg** [comment]
+1

**Comment by admincopm** [comment]
![image](https://user-images.githubusercontent.com/127429945/226826808-710ea4d7-e4af-49cb-9ef0-9e124ddc3bc2.png)

**Comment by adlered** [comment]
收到:)

**Comment by turingzz** [comment]
+1

**Comment by adlered** [comment]
已解决
