### ISSUE TITLE
新功能需求：博文中 URL 直接打开

### ISSUE THREAD

**Issue by CHN-STUDENT** [adlered/CSDNGreener#198]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
![image](https://user-images.githubusercontent.com/21209416/226274373-96d7f7a3-c61f-4ce6-a213-2c0fb97c2140.png)
RT，这URL还有个自己复制链接打开，太傻逼了。
文章: https://blog.csdn.net/whahu1989/article/details/106452683
大佬有办法优化么

**Comment by adlered** [comment]
已优化

**Comment by CHN-STUDENT** [comment]
感谢大佬，关于反重定向，找到其他人的方案，大佬或许可以看看，继续优化，俺不是前端看不懂 ... 

https://github.com/axetroy/anti-redirect
