### ISSUE TITLE
去除底部广告

### ISSUE THREAD

**Issue by iamsunxing** [AdlerED/CSDNGreener#2]
修改后部分代码如下：
function killAll() {
    //核心代码
    //CLASSES
    var classList = new Array(
        // ****** 主页 *****
        //头部广告
        "banner-ad-box",
        //右侧广告
        "slide-outer",
        //顶栏无用选项
        //APP
        "app-btn",
        //VIP
        "vip-caise",
        //右侧浮窗(客服、客户端二维码)
        "csdn-side-toolbar",
        //右侧详情
        "persion_article",
        //顶部轮播
        "carousel",
        // ****** 文章页 ******
        //快来写博客吧
        "blog_tip_box",
        //推荐关注用户
        "blog-expert-recommend-box",
        //右侧工具栏（注释原因：收藏消失）
        //"tool-box",
        //右下角VIP
        "meau-gotop-box",
        //广告
        "mediav_ad",
        "pulllog-box",
        "recommend-ad-box",
        "box-shadow",
        "type_hot_word",
        "fourth_column",
        //高分辨率时右侧文章推荐
        "right-item",
        // ****** 下载 ******
        "fixed_dl",
        "indexSuperise",
        // ****** 论坛 ******
        //推荐广告
        "bbs_feed_ad_box",
        'recommend-ad-box', //底部相关文章里面的广告
        'type_hot_word',    //底部相关文字里面的热词提示
        'recommend-box',     //底部相关文章
        'pulllog-box',     //底部蓝色flex属性的广告栏+登录注册框
    );

**Comment by AdlerED** [comment]
你好！非常感谢你的Issue，更新后的版本会在今天下午推送！
