### ISSUE TITLE
能否让宽度随浏览器变化？

### ISSUE THREAD

**Issue by LeonG7** [AdlerED/CSDNGreener#20]
有时候会分屏工作，但是文章的宽度还是全屏宽度，不得不拖动左右滚动条看文章或者切回全屏。
希望能把宽度改为随着浏览器窗口大小自适应。不知道方不方便，感谢

**Comment by AdlerED** [comment]
好的

**Comment by LeonG7** [comment]
由衷感谢，你的插件帮了我很多忙，我可以专注于文章内容了

**Comment by AdlerED** [comment]
新版本已经有宽度自适应功能了，请更新后体验，感谢你的建议！
