### ISSUE TITLE
ReferenceError: jQuery is not defined 

### ISSUE THREAD

**Issue by yangliu-1995** [adlered/CSDNGreener#204]
你好 我是 iOS 平台的一个浏览器开发者，我们支持油猴规范，在使用您脚本时发现了如下报错，
ReferenceError: jQuery is not defined 
我看了在脚本中没有 require jQuery ，所以导致了这个错误，我想知道是不是油猴默认带了 jQuery

**Comment by zcattacz** [comment]
Same issue on PaleMoon 23.1+GM3.31.4.
