### ISSUE TITLE
目前CSDN复制时会弹窗登录

### ISSUE THREAD

**Issue by LittleWhiteMouse9527** [adlered/CSDNGreener#206]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：

使用插件后，目前复制的时候，会弹窗登录，并且复制的内容无效。

![image](https://user-images.githubusercontent.com/44833045/237055512-6dc28a0d-bb90-4b49-aee4-7f263ad5f2ee.png)

**Comment by cascax** [comment]
+1
