### ISSUE TITLE
能否去除右上角“记录你的技术成长历程”的提示

### ISSUE THREAD

**Issue by ruichima** [adlered/CSDNGreener#21]
您好，阅读任意博客时，右上角总有“记录你的技术成长历程”的提示，如下图，能否尝试去除呢？
chrome 80.0.3987.149
![2020-03-30_100556](https://user-images.githubusercontent.com/61648322/77868929-6afb1e80-726f-11ea-8c81-6aa22976288d.png)

**Comment by adlered** [comment]
安排

**Comment by adlered** [comment]
搞定，请点击油猴的“用户脚本检查更新”，更新到最新版本，感谢你的反馈！:smile:

**Comment by ruichima** [comment]
谢谢您！
