### ISSUE TITLE
由于屏蔽了一些网址，导致插件对部分广告屏蔽会产生异常

### ISSUE THREAD

**Issue by superzmy** [adlered/CSDNGreener#22]
我用域名拦截屏蔽了一些百度、谷歌的广告网址后
类似
document.getElementsByClassName("column-advert-box")[0].style.display="none";
这个的执行会抛出异常，建议加一些try catch！

**Comment by adlered** [comment]
收到了，谢谢

**Comment by adlered** [comment]
我尝试了一下，try {} catch (err) {} 貌似没法阻止一些 err 的产生，麻烦直接提个 PR，多谢啦。
