### ISSUE TITLE
增加 将www.elecfans.com 网站,添加广告过滤,人性化脚本的功能

### ISSUE THREAD

**Issue by hbtbisg** [adlered/CSDNGreener#221]
> 加入 QQ 群 1042370453 可直接与作者沟通

CSDN广告完全过滤、人性化脚本优化非常好用,希望有机会能将 www.elecfans.com 也增加类似的脚本.

**Comment by irkbyxfcqjelz** [comment]
浏览器添加过滤广告扩展就可以了比如AdGuard

**Comment by irkbyxfcqjelz** [comment]
> > 加入 QQ 群 1042370453 可直接与作者沟通
> 
> CSDN广告完全过滤、人性化脚本优化非常好用,希望有机会能将 [www.elecfans.com](http://www.elecfans.com) 也增加类似的脚本.

添加广告过滤器就可以了比如AdGuard？
