### ISSUE TITLE
字体变得好小

### ISSUE THREAD

**Issue by ngrok-add** [adlered/CSDNGreener#232]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
![微信截图_20231113161131](https://github.com/adlered/CSDNGreener/assets/9362876/05ccbe96-9c47-430c-950a-ef370de9131b)

**Comment by wsd1585-fuqi** [comment]
+1，完全看不清内容

**Comment by BigerPatax** [comment]
![image](https://github.com/adlered/CSDNGreener/assets/56615748/0cdcb001-28af-4a13-835c-538612e51145)
这里改成跟上面一样就好了，不知道为啥要设置这么小的字体

**Comment by adlered** [comment]
已修复，因为csdn样式改了
