### ISSUE TITLE
内容看不到了

### ISSUE THREAD

**Issue by lxccc812** [adlered/CSDNGreener#239]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
csdn 看不到内容

![image](https://github.com/adlered/CSDNGreener/assets/110974969/c6f883dc-a48d-4d23-9118-78f75ac551d2)

**Comment by 1234567Yang** [comment]
![image](https://github.com/adlered/CSDNGreener/assets/113082249/7bd7d568-3d26-41dd-89e5-bc74c2a774ed)
+1

**Comment by adlered** [comment]
> https://blog.csdn.net/weixin_42100963/article/details/106140938 ![image](https://private-user-images.githubusercontent.com/113082249/292045287-7bd7d568-3d26-41dd-89e5-bc74c2a774ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTYyNjYsIm5iZiI6MTcwMzE1NTk2NiwicGF0aCI6Ii8xMTMwODIyNDkvMjkyMDQ1Mjg3LTdiZDdkNTY4LTNkMjYtNDFkZC04OWU1LWJjNzRjMmE3NzRlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQxMDUyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGY1ZGM0YTljNzlkMTE0ZGI3ODI0OTVjYWNhNjA2YTljNjhiMGQxNmY2ZTIyOWYxYTc5MDE1NTBiYzBhMDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tmcUAhtPgZj-AGOyq_RUX2fvNKE0Bm_F5b_iu7GFnow)

该问题已修复，请更新4.2.2后重试，感谢两位的反馈。
