### ISSUE TITLE
能不能给这个烦人的猴子去掉，一点用没有还碍事

### ISSUE THREAD

**Issue by 1456745460** [adlered/CSDNGreener#255]
> 加入 QQ 群 1042370453 可直接与作者沟通
能不能给这个烦人的猴子去掉，一点用没有还碍事
### 请描述你遇到的问题：
![Snipaste_2024-04-02_17-23-24](https://github.com/adlered/CSDNGreener/assets/49932290/7645f691-1e6e-42cb-a6b3-4fd16900f31f)

**Comment by 1393037860** [comment]
如果作者新版本没隐藏这个猴子, 你可以找到这个dom把它加进删除数组里面重新运行脚本哈哈哈

**Comment by 1393037860** [comment]
> 收到，不好意思刚看到，下个版本屏蔽

哇作者竟然抄送给我了，合影留念
