### ISSUE TITLE
代码块格式，无换行

### ISSUE THREAD

**Issue by YoungKang1222** [adlered/CSDNGreener#258]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
![image](https://github.com/adlered/CSDNGreener/assets/30460985/5ce9f4ff-b4c0-4ecf-811e-14f987516c1e)

**Comment by adlered** [comment]
你好，此问题请反馈给发文的博主，他复制粘贴的问题
