### ISSUE TITLE
屏蔽您的缩放不是100%的提示

### ISSUE THREAD

**Issue by CHN-STUDENT** [adlered/CSDNGreener#26]
![image](https://user-images.githubusercontent.com/21209416/81717649-6308de00-94ad-11ea-9e8a-a183b50d7457.png)

如题，我打开文章提示我屏幕缩放不是100%，我手工关掉了，现在不出现了，无法重现，这个您觉得是否有必要也优化下屏蔽下？感谢。

文章测试地址：https://blog.csdn.net/taiyangdao/article/details/51578386

**Comment by adlered** [comment]
已更新，感谢建议，请更新到最新版本体验~
