### ISSUE TITLE
有没有办法把CSDN的body background-image 彻底去除？

### ISSUE THREAD

**Issue by ktech0** [adlered/CSDNGreener#270]
CSDN 的 background-image 动态图 `https://csdnimg.cn/release/blogv2/dist/pc/themesSkin/skin-whitemove/images/bg.gif` 太恶心了，即使看不到，依然跑在后台严重浪费资源

**Comment by ktech0** [comment]
我知道了，建议增加：`document.querySelector('link[href^="https://csdnimg.cn/release/blogv2/dist/pc/themesSkin/skin-whitemove/"]').href="";`

**Comment by adlered** [comment]
感谢反馈，近期更新下
