### ISSUE TITLE
免登录复制好像又不能用了

### ISSUE THREAD

**Issue by nukewarrior** [adlered/CSDNGreener#28]
脚本版本：2.2.9
chrome版本： 81.0.4044.138（正式版本） （64 位）
系统版本：macOS 10.15.4

**Comment by adlered** [comment]
哦豁，是嘛，稍等我看一下

**Comment by adlered** [comment]
我这边测试是可以的哦，麻烦试一下还是否工作，我是Chrome 81 macOS 10.14

**Comment by nukewarrior** [comment]
我刚刚又试了下，还是不行，特意重新安装了脚本并重启了Chrome也不行

具体打开的csdn页面是

> https://blog.csdn.net/weixin_40841731/article/details/84987079

![image](https://user-images.githubusercontent.com/10683831/82678274-e4b1f600-9c7b-11ea-8aa3-742d22f07940.png)

**Comment by adlered** [comment]
刚刚清除Cookie试了下，确实出现问题了，已修复，请更新脚本（或等待自动更新），感谢~
