### ISSUE TITLE
csdn不能复制了，一复制就会弹出登录页面

### ISSUE THREAD

**Issue by WLDDKK** [adlered/CSDNGreener#284]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
csdn不能复制了，一复制就会弹出登录页面
![image](https://github.com/user-attachments/assets/73e996d7-fe0c-4f4d-89c8-61ec83eeac79)

**Comment by adlered** [comment]
麻烦更新到最新版本试一下，我这边测试没问题。
