### ISSUE TITLE
新功能建议 - 夜间模式

### ISSUE THREAD

**Issue by AlexLWT** [adlered/CSDNGreener#31]
个人比较喜欢高对比度看东西 所以希望dalao可以添加一个黑底黄字的皮肤切换模式
希望这个模式可以保存设置 设置一次用一辈子0.0

**Comment by adlered** [comment]
最近比较忙，推迟半个月编写:smile:

**Comment by adlered** [comment]
目前CSDN有黑暗模式皮肤，黑底白字，目前先做这个开关，黄字的话先等等看官方是否会适配吧，感谢意见~
