### ISSUE TITLE
文章无法全屏幕显示了

### ISSUE THREAD

**Issue by CHN-STUDENT** [adlered/CSDNGreener#32]
Rt，之前的版本是铺满整个屏幕的，不知道是改版的原因么？
![image](https://user-images.githubusercontent.com/21209416/83942400-ae50ab00-a825-11ea-9429-3f1e00d4d6c1.png)
测试链接：https://blog.csdn.net/Davie_Liu/article/details/90340317
版本v2.4.1

**Comment by adlered** [comment]
有用户反馈文章居中比较好一些，同时也对窄屏做了优化，如有优化意见请追加，谢谢~

**Comment by CHN-STUDENT** [comment]
@adlered 嗯，但是表示宽屏习惯了，能不能加个按钮做宽屏显示呢？

使用用户越来越多真是很不错，感谢您的无私奉献！

**Comment by adlered** [comment]
应该的~下个版本我会抽空搞个弹出式菜单，把各种选项放进去，感谢你的建议与支持哦。
