### ISSUE TITLE
设置界面问题

### ISSUE THREAD

**Issue by qqqqql** [adlered/CSDNGreener#35]
![image](https://user-images.githubusercontent.com/58932048/84149990-d80f0980-aa93-11ea-9395-358e29634fc0.png)
设置内容存在遮挡

**Comment by adlered** [comment]
收到了，下个版本修复，谢谢

**Comment by adlered** [comment]
你好，Bug已经体验，请更新到最新版本体验哦，感谢你的建议。

**Comment by qqqqql** [comment]
好的，感谢！





------------------ 原始邮件 ------------------
发件人: Adler Chan <notifications@github.com&gt;
发送时间: 2020年6月10日 00:19
收件人: adlered/CSDNGreener <CSDNGreener@noreply.github.com&gt;
抄送: qqqqql <827547789@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[adlered/CSDNGreener] 设置界面问题 (#35)





 
你好，Bug已经修复，请更新到最新版本体验哦，感谢你的建议。
