### ISSUE TITLE
怎么提高脚本加载速度

### ISSUE THREAD

**Issue by Rovever** [adlered/CSDNGreener#37]
现在网速都还不错，通常页面已经加载出来，要登上几秒钟脚本才生效。需要修改什么参数可以缩短脚本等待时间呢

**Comment by adlered** [comment]
`286` 行，`500` 改为 `0`  
`292` 行，`600` 改为 `0`  
加载速度应该会有提高，实际上进度条并非真实的优化进度，可以修改尝试下，下个版本我做优化~

**Comment by adlered** [comment]
新版本已经优化加载速度，更新即可，不需要自己修改了哦。

**Comment by Rovever** [comment]
谢谢啦，现在加载速度快很多了
