### ISSUE TITLE
速度有些慢

### ISSUE THREAD

**Issue by JoyfulAndSpeedyMan** [adlered/CSDNGreener#38]
我只是吐槽一下，每次打开CSDN都需要等一会才能出现过滤后的界面。当然，我知道是js的限制，作者做的已经很不错了，如果要是更快一点就更好了😁😁

**Comment by adlered** [comment]
哈哈哈，流程性原因，再加快速度可能就要从自己的网络质量下手了，我还会继续优化，感谢你对 CSDNGreener 的支持哦。:smile:
