### ISSUE TITLE
有个小建议

### ISSUE THREAD

**Issue by Granado** [adlered/CSDNGreener#39]
我期望绿化后能有配置看到 作者最新文章 和 分类专栏（如下图）。
因为有时候可能发现作者的文章原创多，质量好，能够快速看到他有哪些分类和新的文章，帮助我发现高质量文章和更多作者文章中我感兴趣的。
<img width="290" alt="分类" src="https://user-images.githubusercontent.com/11748519/84721211-b7264700-afb2-11ea-905a-b9985c859d0e.png">
<img width="303" alt="最新" src="https://user-images.githubusercontent.com/11748519/84721219-bab9ce00-afb2-11ea-8431-98acafebc457.png">

**Comment by adlered** [comment]
好的，近期会做更新，谢谢。

**Comment by adlered** [comment]
请更新脚本后体验哦，大部分功能都可以选择显示或者隐藏了，欢迎再提意见~

**Comment by Granado** [comment]
> 请更新脚本后体验哦，大部分功能都可以选择显示或者隐藏了，欢迎再提意见~

多谢大佬
