### ISSUE TITLE
推荐内容能否加上开关？

### ISSUE THREAD

**Issue by lukemin** [AdlerED/CSDNGreener#4]
我觉得推荐内容挺有用的，希望保留。

**Comment by AdlerED** [comment]
好提议！之前我也想过这个问题。下午之前会更新。感谢！

**Comment by AdlerED** [comment]
你好！功能已经成功写好。请更新至1.4.0体验！:smile:

**Comment by lukemin** [comment]
谢谢

**Comment by AdlerED** [comment]
续：你好，刚刚我发现这个按钮只能在当前帖子下有效，现在按一下隐藏/显示，在整个CSDN都能应用了，应该会更方便一些，望知悉！
