### ISSUE TITLE
建议增加自动隐藏顶栏、底栏等功能

### ISSUE THREAD

**Issue by abc1044** [adlered/CSDNGreener#41]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
建议增加自定义自动隐藏顶栏、底栏等功能。希望可以考虑以下三点自定义功能：
1、阅读时自动隐藏顶栏/底栏
2、自动隐藏右下角的客服和举报按钮
3、魔改底栏按钮功能，去除文字/换成emoji等。（目前版本3.1.4中，页面调窄之后，底栏文字会换行，比较占地方）

![2020 0617 反馈2](https://user-images.githubusercontent.com/18114052/84841963-7db70f80-b076-11ea-8884-ba337ccdd1bf.png)

**Comment by adlered** [comment]
谢谢，下个版本改进。

**Comment by adlered** [comment]
底栏和侧栏下个版本做，顶栏已经加入自动隐藏选项

**Comment by abc1044** [comment]
> 底栏和侧栏下个版本做，顶栏已经加入自动隐藏选项

已在v3.2.1使用自动隐藏顶栏，建议优化快速显示顶栏功能...
就是...浏览的时候自动隐藏了，很方便。这时候想去顶栏跳转，就需要翻到顶部才显示了。

是否可以优化成以下交互：
- 往下翻的时候/静止的时候顶栏自动隐藏；
- 往上翻的时候顶栏重新出现。

**Comment by adlered** [comment]
我在体验时也发现了这个问题，没有问题，下个版本会修改。
很用心的反馈报告，感谢！
