### ISSUE TITLE
关于强制白色主题和darkreader插件夜间模式兼容问题

### ISSUE THREAD

**Issue by abc1044** [adlered/CSDNGreener#42]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
打开使用darkreader夜间模式的时候，背后会有一块白色背景。（可能是darkreader的问题..没开强制白色主题，也会有一块背景无法去除）

是否可以直接去除背景图案，或者脚本集成夜间模式。

**Comment by abc1044** [comment]
附上测试页面：https://blog.csdn.net/FL63Zv9Zou86950w/article/details/106821276

强制白色+darkreader夜间模式：
![image](https://user-images.githubusercontent.com/18114052/85243837-7bd5bd80-b475-11ea-9ec8-3d6085c4cf2b.png)
![image](https://user-images.githubusercontent.com/18114052/85243852-83956200-b475-11ea-8906-cb6b3bbef730.png)

**Comment by adlered** [comment]
我大概知道原因在哪里了，这个是我的锅，感谢。

**Comment by adlered** [comment]
下个版本会做修复
