### ISSUE TITLE
关于脚本新增夜间模式的建议

### ISSUE THREAD

**Issue by abc1044** [adlered/CSDNGreener#43]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
脚本是否可以集成夜间模式：

- 手动设置夜间模式
- 夜间模式跟随系统设置（win10）
- 夜间模式计划启用时间段，自定义
- 去除主题背景色块

**Comment by adlered** [comment]
感谢你的意见：
* 夜间模式代码量比较大，正在开发中，敬请期待哦
* CSDNGreener作为一款脚本，是无法获取Windows的夜间模式开启状态的
* 没有问题，后续会开发
* 现在已经有强制白色背景的功能了，后续也会考虑更高级的方式，独立一个主题控制

**Comment by Fxiao1** [comment]
个人建议还是找找浏览器插件更好点，毕竟你不可能在csdn里面是夜间模式，换个网站却又刺瞎眼吧（夜间模式一般会稍微提高一点亮度）

**Comment by adlered** [comment]
是的，CSDNGreener已增加Dark Reader适配模式，黑夜模式还在开发中。

**Comment by sky5454** [comment]
CSS的 filter 属性可以轻易实现夜间模式
https://developer.mozilla.org/zh-CN/docs/Web/CSS/filter
