### ISSUE TITLE
火狐浏览器 右侧边栏热门文章显示不全

### ISSUE THREAD

**Issue by git10135405** [adlered/CSDNGreener#47]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
![image](https://user-images.githubusercontent.com/35558611/85380739-dc492580-b56f-11ea-88a6-6b2c1449e397.png)
火狐浏览器 右侧边栏热门文章显示不全 建议可滚动！

**Comment by adlered** [comment]
收到了，谢谢！

**Comment by adlered** [comment]
麻烦提供一个出问题的页面地址

**Comment by adlered** [comment]
![image](https://user-images.githubusercontent.com/6754458/85511231-fd228100-b62a-11ea-94ee-756dc07942d5.png)

这边测试是没问题的哈，麻烦提供一个出问题的页面地址。

**Comment by git10135405** [comment]
![图片](https://user-images.githubusercontent.com/35558611/85514855-0e6d8c80-b62f-11ea-8652-cf754278f0d0.png)
这些跟我一样勾选下再看

**Comment by adlered** [comment]
![image](https://user-images.githubusercontent.com/6754458/85570195-be5dec80-b665-11ea-84a4-23c964ffa41b.png)

是这个情况吗？

**Comment by git10135405** [comment]
不太一样，我的右侧边栏没有那个长活动条，只有上面推荐的有而已😂

**Comment by adlered** [comment]
麻烦更新到最新版本，再试一下。最新版本是：`v3.2.9`

**Comment by adlered** [comment]
最新版已经优化了这个长活动条了

**Comment by git10135405** [comment]
我节后再试试

**Comment by adlered** [comment]
ok
