### ISSUE TITLE
该脚本无法彻底移除，在另一个源安装后同时存在

### ISSUE THREAD

**Issue by tor2016** [adlered/CSDNGreener#48]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：

![image](https://user-images.githubusercontent.com/22971551/85420486-d5d5a080-b5a5-11ea-8c5b-f6d6fcc47947.png)

**Comment by adlered** [comment]
麻烦在脚本设置里先删除原有的脚本（按照 [迁移教程](https://doc.stackoverflow.wiki/web/#/25) 进行操作）

**Comment by adlered** [comment]
在油猴插件-管理面板里删掉旧的脚本

**Comment by tor2016** [comment]
![image](https://user-images.githubusercontent.com/22971551/85420923-6a400300-b5a6-11ea-9285-cdddbd875dcb.png)
我就是按照迁移教程来的👆现在就算是全删除脚本也生效

**Comment by adlered** [comment]
全部删除以后，重启浏览器脚本还在？

**Comment by adlered** [comment]
够邪门的，除了油猴还有别的脚本运行插件吗？

**Comment by tor2016** [comment]
这是个好问题，我不仅重启了浏览器，还重启了计算机
![image](https://user-images.githubusercontent.com/22971551/85423370-34504e00-b5a9-11ea-9b79-1ca61d01a1d8.png)
如果脚本有运行，红框中对油猴图标应该有气泡才正常～

**Comment by tor2016** [comment]
![image](https://user-images.githubusercontent.com/22971551/85423515-5ba71b00-b5a9-11ea-898a-34c15ca45441.png)
这样应该看的更详细👆

**Comment by adlered** [comment]
不可能呀。。。禁用油猴插件以后还有吗？如果有的话，脚本是不是被安装到别的插件（如暴力猴）上面了？

**Comment by tor2016** [comment]
并没有，我只使用了油猴插件～

**Comment by blackboxo** [comment]
同样遇到了这个问题

**Comment by adlered** [comment]
出现该问题可能会有两种情况：

1. 没有删除旧的脚本，请到脚本管理中卸载旧版本
2. 可能安装了多个脚本管理器插件，例如：TamperMonkey、MeddleMonkey、ViolentMonkey，请认真核查各个脚本管理器已安装的内容，并尽可能的只保留一个脚本管理器，以免出现兼容性问题。

**Comment by adlered** [comment]
麻烦重装下插件再试试看哦

**Comment by DirectorCW** [comment]
我今天遇到了同样的情况，都是最新版本。并没有安装其他脚本管理器。
