### ISSUE TITLE
文章管理中心，上方栏目不能正常显示

### ISSUE THREAD

**Issue by ImViper** [adlered/CSDNGreener#49]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
在文章管理中心的时候，上方的栏目会出现鬼畜，就是滚动到最上方的时候不能正常显示，而是会跳动。
![image](https://user-images.githubusercontent.com/60597225/85427935-04a44480-b5af-11ea-89ca-a16adfdb101e.png)
建议:不识别文章管理中心。

**Comment by adlered** [comment]
已修复。
