### ISSUE TITLE
gap is too large

### ISSUE THREAD

**Issue by iamsunxing** [AdlerED/CSDNGreener#5]
I use the latest chrome(2019.8.13), and the gap in top is too large.
![image](https://user-images.githubusercontent.com/23116686/62922113-2fddd500-bddd-11e9-961b-08866081c4c4.png)

**Comment by AdlerED** [comment]
got it! i'm trying to fix this issue will update in next version. THX so much!

**Comment by AdlerED** [comment]
The problem has been fixed, plz do upgrade to the lastest version. Thanks again!
