### ISSUE TITLE
建议把创作中心的按钮添加回去

### ISSUE THREAD

**Issue by ImViper** [adlered/CSDNGreener#50]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
添加回创作中心的按钮，或者可以选择。对写博客的人会更加友好。不用每次打开文章管理再去打开编辑器。

**Comment by adlered** [comment]
OK

**Comment by adlered** [comment]
创作中心按钮在控制面板里可以选择开启或隐藏咯。
