### ISSUE TITLE
关于屏蔽首页-博客的部分模块功能

### ISSUE THREAD

**Issue by abc1044** [adlered/CSDNGreener#51]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
[首页-博客]页面有一些类似推广，或者不太重要的内容，希望可以增加自定义屏蔽按钮。
如图红框所示：
![image](https://user-images.githubusercontent.com/18114052/85481498-7e125600-b5f4-11ea-8bde-7163bf87478e.png)
https://blog.csdn.net/

**Comment by adlered** [comment]
多加一个按钮工作量较多，下个版本做，谢谢

**Comment by abc1044** [comment]
按钮或者设置选项都可以~你看看怎么合适怎么来~
对了，是否可以把绿色的“更新提示”改成几秒自动消失的形式，不用经常手动点击关闭，可能会更舒服一些。

**Comment by adlered** [comment]
暂时不考虑修改，因为新用户不知道绿化按钮在哪儿，可能会造成误会~
