### ISSUE TITLE
设置里面的右侧栏定制选项，全都不起作用

### ISSUE THREAD

**Issue by sle1008** [adlered/CSDNGreener#54]
如下图所示：
![image](https://user-images.githubusercontent.com/39543446/85976135-6bd95300-ba0c-11ea-8acb-0255212ddb9c.png)
保存设置之后，还是mei'you没有任何右侧栏，只有正文。
![image](https://user-images.githubusercontent.com/39543446/85976208-8d3a3f00-ba0c-11ea-87d2-3e6feebfc3b1.png)
内容忽略，只看样式，保存之后左右两侧还是啥都没有。有时候我需要看一看作者的其他文章，所以想要留着作者卡片。

**Comment by adlered** [comment]
屏幕太小了，右边地方不够。改成小屏幕模式试试看。

**Comment by adlered** [comment]
第一个选项，窗口尺寸选择，点击小窗口

**Comment by adlered** [comment]
Issue 先关闭了哦。如果还有问题请继续回复

**Comment by sle1008** [comment]
> 屏幕太小了，右边地方不够。改成小屏幕模式试试看。

我之前说的有一点不对。这个网页原版是作者名片在左边，你也可以看到关闭后左边的空间是比右边大的。所以应该不是屏幕太小，右边空间不够的情况。不过小屏幕也试过了，仍然不起作用

**Comment by adlered** [comment]
CSDNGreener重写了前端逻辑，所有内容都在内侧显示，左侧只会显示文章。调成小屏幕还不起作用，请拖大浏览器窗口
