### ISSUE TITLE
不显示右侧栏

### ISSUE THREAD

**Issue by xming521** [adlered/CSDNGreener#55]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
选的小屏幕窗口也拖到最大了 还是不显示右侧栏
![image](https://user-images.githubusercontent.com/32786500/86528280-18b64300-bed9-11ea-8da0-3519b2167627.png)
![image](https://user-images.githubusercontent.com/32786500/86528296-426f6a00-bed9-11ea-98d5-d64a07c1394f.png)

**Comment by adlered** [comment]
这个问题最新版已经解决了，麻烦手动检查下更新。

**Comment by xming521** [comment]
额 可是这已经是3.3.5 最新版本了

**Comment by xming521** [comment]
> 这个问题最新版已经解决了，麻烦手动检查下更新。

额 可是这已经是3.3.5 最新版本了

**Comment by adlered** [comment]
看起来分辨率有点低，麻烦加QQ群交流一下，Issue交流不太方便 :smile:
