### ISSUE TITLE
打印问题

### ISSUE THREAD

**Issue by ghmole** [adlered/CSDNGreener#56]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
在chrome中，鼠标右键打印时，页面显示错误，只显示一部分

**Comment by adlered** [comment]
你好，经过测试是CSDN的锅。关闭脚本之后仍旧排版错误
建议调用 Chrome 的 “全页面” 截图功能生成图片，然后打印图片 :)
