### ISSUE TITLE
建议：关于设置页面的"保存"/"关闭"按钮位置建议

### ISSUE THREAD

**Issue by abc1044** [adlered/CSDNGreener#57]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：

- 在设置界面，可以把关闭窗口的按钮固定在右上角。
- 更改设置之后，需要翻到最下方点保存按钮，然后翻到最上方点关闭按钮，有一些繁琐。可以考虑集成到一个按钮，如：保存并关闭。
![issue](https://user-images.githubusercontent.com/18114052/86739731-ae340d00-c068-11ea-90c5-06cdc2a4720b.png)

**Comment by adlered** [comment]
非常感谢，请期待v3.3.6
