### ISSUE TITLE
创作中心的菜单栏一直有问题啊

### ISSUE THREAD

**Issue by ImViper** [adlered/CSDNGreener#58]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
![image](https://user-images.githubusercontent.com/60597225/87870752-a3b93200-c9dd-11ea-9922-d7b997737b81.png)

首先是显示有问题，而且经常会莫名的滚动。干脆不要识别创作中心网站好了。

**Comment by adlered** [comment]
收到，正在解决

**Comment by adlered** [comment]
我这边测试创作中心没有问题，麻烦提供下出现问题的页面地址。

**Comment by ImViper** [comment]
> 我这边测试创作中心没有问题，麻烦提供下出现问题的页面地址。

https://mp.csdn.net/console/home
https://mp.csdn.net/console/article

**Comment by ImViper** [comment]
就这个console下的基本都有问题
![image](https://user-images.githubusercontent.com/60597225/87890405-f68bfb80-ca68-11ea-8139-e238ae73078e.png)

**Comment by adlered** [comment]
哈喽，问题已经修复，新版本已经推送了。  
请手动检查更新到 `3.3.7` 试试看，如有问题欢迎继续反馈。谢谢 :)
