### ISSUE TITLE
老哥，希望文字可以居中（强迫症泪目

### ISSUE THREAD

**Issue by DarcyXv** [adlered/CSDNGreener#59]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
如题

**Comment by adlered** [comment]
麻烦截个图说明想要实现的效果 :)

**Comment by DarcyXv** [comment]
![批注 2020-07-27 171459](https://user-images.githubusercontent.com/58544318/88525152-d04bfa00-d02c-11ea-859c-3fbaf2565b85.png)
就是这块 希望可以放在页面的中间。我也是学计算机的，但是才大一，目前只掌握了后端开发方面的一些粗浅知识，不然我自己动手也不用麻烦老哥了555~

**Comment by adlered** [comment]
这个页面居中由于csdn的代码比较混乱，暂时没法实现，建议使用小屏幕模式，可以靠左哈哈。

**Comment by DarcyXv** [comment]
害  我之前用的一款是可以实现的，但是我电脑重做了系统，我记不得是哪个了，因为原来的那个是聚合的，我把关于csdn的部分自己提取出来的，我再找找
