### ISSUE TITLE
9月4号开始csdn无限弹登录页面

### ISSUE THREAD

**Issue by dwdcth** [AdlerED/CSDNGreener#6]
如题

**Comment by AdlerED** [comment]
感谢，已经收到。希望可以加一些复现过程

**Comment by AdlerED** [comment]
我也遇到过一次这个问题，但后来复现不出来了。换系统和浏览器都无法复现，刚刚测试，未登录状态下还是正常的

**Comment by AdlerED** [comment]
请提供一下浏览器版本，系统环境，出现问题的URL

**Comment by dwdcth** [comment]
Chromium 版本 76.0.3809.100（正式版本）Built on Ubuntu , running on Ubuntu 18.04 （64 位）
Url [https://blog.csdn.net/Gamer_gyt/article/details/93927941](url)

**Comment by AdlerED** [comment]
问题已经复现，感谢，尽快解决

**Comment by dwdcth** [comment]
不客气，谢谢～

**Comment by AdlerED** [comment]
你好，感谢你的反馈，问题已经修复了，请点击油猴插件手动更新，如有问题欢迎再提Issue~
