### ISSUE TITLE
勾选显示博主信息还是会被过滤，还有那是在左侧边栏但插件设置里是右侧边栏

### ISSUE THREAD

**Issue by Justin-Young** [adlered/CSDNGreener#62]
> 加入 QQ 群 1042370453 可直接与作者沟通

**Comment by Justin-Young** [comment]
![Uploading image.png…]()

**Comment by Justin-Young** [comment]
保存了设定左侧作者信息栏仍无法显示，看设置里设置的是右侧信息栏（而博主的信息栏是在左边），难道因为这个

![image](https://user-images.githubusercontent.com/53030626/91166195-8ece6d80-e704-11ea-9b0c-dac71e208261.png)

**Comment by adlered** [comment]
博主信息会在右边栏显示，请修改显示模式尝试。

**Comment by adlered** [comment]
<img width="1792" alt="截屏2020-08-25 下午9 43 58" src="https://user-images.githubusercontent.com/6754458/91181911-170c3d00-e71c-11ea-85a2-ba8bb78d4df6.png">
