### ISSUE TITLE
还是会出现登录框

### ISSUE THREAD

**Issue by azui999** [adlered/CSDNGreener#68]
> 加入 QQ 群 1042370453 可直接与作者沟通

**Comment by adlered** [comment]
问题已修复，登录框会给它秒杀掉，概率性问题，如果有登录框无法关掉的情况请提供URL哦。

**Comment by azui999** [comment]
> 问题已修复，登录框会给它秒杀掉，概率性问题，如果有登录框无法关掉的情况请提供URL哦。

好的,谢谢回复
