### ISSUE TITLE
关于Chrome页面保存为PDF时候遇到的问题

### ISSUE THREAD

**Issue by Xiaoyi98619** [adlered/CSDNGreener#69]
当使用Chrome并启用脚本的时候，保存页面为PDF时页面内容大部分缺失，关闭脚本后刷新页面即可正常保存PDF
![1](https://user-images.githubusercontent.com/20264578/96330337-e941d580-1086-11eb-9458-715a36adffda.JPG)
![2](https://user-images.githubusercontent.com/20264578/96330343-eb0b9900-1086-11eb-9d1b-8edbd94960df.JPG)
![3](https://user-images.githubusercontent.com/20264578/96330347-eba42f80-1086-11eb-9f0d-de4a0109ee8c.JPG)

**Comment by adlered** [comment]
问题已收到，谢谢
