### ISSUE TITLE
评论区点击查看回复后，已经展开的评论会收起

### ISSUE THREAD

**Issue by programmerZe** [AdlerED/CSDNGreener#7]
![GIF](https://user-images.githubusercontent.com/32977308/64598820-f5228900-d3ea-11e9-9fba-b4944c34466c.gif)

**Comment by AdlerED** [comment]
你好，反馈已经收到，正在查实并修复，十分感谢！
另：请提供出现问题的URL地址，使用的浏览器版本，以及登录与未登录是否都出现该情况，谢谢！

**Comment by programmerZe** [comment]
URL：https://blog.csdn.net/guleileo/article/details/80767966
浏览器：Chrome 76.0.3809.132
未登录出现该情况，因为没有csdn账号所以不知道登录以后会不会出现

**Comment by AdlerED** [comment]
收到了！这边经过核实，确认在未登录情况下会产生此问题，登录后可以正常使用评论功能。原因是CSDN限制未登录用户只能查看3条评论，本脚本解除了3条评论的限制，但没有做展开评论的相关屏蔽。
新版本会修复该问题，届时我会通过该Issue与您沟通，再次感谢！

**Comment by AdlerED** [comment]
你好！问题已经修复完毕，请点击你的油猴插件->用户脚本检查更新，将脚本更新到1.4.9版本。如有问题，欢迎继续Issue！

**Comment by programmerZe** [comment]
非常感谢
