### ISSUE TITLE
页面右侧出现部分广告，需要进行适配

### ISSUE THREAD

**Issue by abc1044** [adlered/CSDNGreener#70]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
版本v3.4.1，页面右侧含有部分广告，脚本需要进行适配。谢谢作者！

含广告页面截图：
![image](https://user-images.githubusercontent.com/18114052/96594027-c0d30900-131c-11eb-82a6-3f9d54c45ecf.png)

**Comment by adlered** [comment]
收到，马上修复
