### ISSUE TITLE
目录显示不了

### ISSUE THREAD

**Issue by 2293736867** [adlered/CSDNGreener#73]
# 环境

- Chrome 86.0.4240.111 
- Manjaro

# 目录不能显示

但是其他栏目都可以显示。

![在这里插入图片描述](https://img-blog.csdnimg.cn/20201024092516123.png)

# 已尝试的解决方案

- 降级到3.4.0，不行
- 降级到3.3.x，但是不适配改版后的CSDN
- 已排除是其他同类型脚本的冲突

**Comment by adlered** [comment]
问题已收到，感谢测试，很快修复问题。
