### ISSUE TITLE
CSDN在HiDPI显示设备上内容不居中的问题

### ISSUE THREAD

**Issue by jacobvv** [adlered/CSDNGreener#74]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：

系统：Win10 20H1
显示器：31寸4k（2160p）
缩放比例：150%
浏览器：Chrome 86
仅安装该脚本

打开CSDN博客页面，博客内容不居中

如图：

<img width="1920" alt="Snipaste_2020-11-02_01-20-42" src="https://user-images.githubusercontent.com/12238067/97809780-093ddf80-1caa-11eb-83cc-a3dc904906d6.png">

对比原版网页：

<img width="1920" alt="Snipaste_2020-11-02_01-24-32" src="https://user-images.githubusercontent.com/12238067/97809808-31c5d980-1caa-11eb-8a77-c98f14e6ce1e.png">

最后，非常感谢作者的脚本~~~

**Comment by adlered** [comment]
请问切换显示模式会有改善吗？

**Comment by jacobvv** [comment]
> 请问切换显示模式会有改善吗？

只有200%时有改善。不过这个问题貌似是因为内容容器margin硬编码导致，需要使用动态适配。

附图：

100%显示比例：
![Snipaste_2020-11-05_22-38-02](https://user-images.githubusercontent.com/12238067/98255159-14e61a80-1fb8-11eb-8287-71902953e534.png)

200%显示比例：
![Snipaste_2020-11-05_22-38-25](https://user-images.githubusercontent.com/12238067/98255200-1dd6ec00-1fb8-11eb-8476-4bdf17d8570b.png)

**Comment by adlered** [comment]
抱歉，因为我这边暂时没有4K的设备可以做测试，如果缩放正常的话还请使用一段时间，等我发了年终奖，就有设备可以测试了 :)
