### ISSUE TITLE
页面放大后，右侧栏消失

### ISSUE THREAD

**Issue by DefetC** [adlered/CSDNGreener#79]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
当页面缩放较大时，右侧栏没地方显示了，就消失了。

在我的15.6寸笔记本上，即使是100%显示比例，也会出现此情况。

100%缩放：
![image](https://user-images.githubusercontent.com/20338520/102306012-64573780-3fb5-11eb-950c-5c3a06442a4f.png)

90%缩放：
![image](https://user-images.githubusercontent.com/20338520/102306063-76d17100-3fb5-11eb-8e51-45148f6a3477.png)

我的脚本设置：
![image](https://user-images.githubusercontent.com/20338520/102306117-949ed600-3fb5-11eb-8db5-704089b14e4c.png)

我的环境：
win10；Edge浏览器。

**Comment by adlered** [comment]
您好，由于CSDN前端框架限制，建议调整浏览器缩放解决该问题。
Feature +1
