### ISSUE TITLE
9.20号打开文章会弹出登录界面

### ISSUE THREAD

**Issue by CHN-STUDENT** [AdlerED/CSDNGreener#8]
测试链接：https://blog.csdn.net/github_35631540/article/details/80278114

症状：打开之后会弹出一个登录页，虽然能净化但是会好烦啊。
登录页地址：https://passport.csdn.net/login?code=public

![image](https://user-images.githubusercontent.com/21209416/65315315-738ce100-dbca-11e9-999c-dcfdc12d3299.png)

系统 Windows10 1809 浏览器 Chrome 77.0.3865.90

请核实并且尝试解决？感谢您！感谢您为我们做出的优秀脚本！

**Comment by AdlerED** [comment]
感谢你的反馈！问题已经收到，我会在最快的时间内解决这个问题！
每次更新都是在和CSDN博弈，CSDN无数次照着净化脚本尝试绕过，太流氓了。

**Comment by AdlerED** [comment]
你好，请确认一下您的脚本版本是否在V1.4.9以上，点击油猴图标-用户脚本检查更新后重试，看看问题是否仍然存在，这个问题之前有出现过，已经修复过了，我使用V1.4.9版本测试没有问题，谢谢！

**Comment by CHN-STUDENT** [comment]
@AdlerED  您好，已经确认是因为我之前装的CSDN屏蔽脚本未更新造成的此问题，您的脚本没有问题，我已经将原来的屏蔽脚本禁用并且使用您的脚本，再次感谢您的帮助和提供这么好的作品！
