### ISSUE TITLE
csdn博客中存在官方的广告博文

### ISSUE THREAD

**Issue by EtherealMingo** [adlered/CSDNGreener#82]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
经常会被标题名吸引点击进去，才发现是广告，非常影响心情。我看到代码渲染每十篇博文中就存在一篇广告，属性值是other，建议在这一块用jQuery的属性选择器remove

**Comment by adlered** [comment]
收到，之前有这方面的脚本，估计官方更新了，我再看看

**Comment by adlered** [comment]
感谢您的建议，已经修复，请更新脚本后尝试。
