### ISSUE TITLE
火狐浏览器总是会失效？

### ISSUE THREAD

**Issue by RaibFlee** [adlered/CSDNGreener#83]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
火狐浏览器总是会失效？这是我电脑的问题吗？

**Comment by adlered** [comment]
请稍等，我测试一下

**Comment by adlered** [comment]
这里测试没有问题，可以具体描述下问题吗？

**Comment by RaibFlee** [comment]
我找到问题了，好像是有一个脚本与你的起冲突了

**Comment by adlered** [comment]
好的，祝你使用愉快，如有问题请继续提出Issue，当前Issue我就先关闭啦。
