### ISSUE TITLE
右侧栏无法显示目录

### ISSUE THREAD

**Issue by zheyuanWang** [adlered/CSDNGreener#84]
[这篇文章](https://blog.csdn.net/heyongluoyao8/article/details/49408131
)是有目录的, 而我在勾选了显示目录的框框之后目录并没有显示
ps. 测试过平铺模式和适应模式, 均无目录
ps. 单独勾选显示目录 (是不是目录显示要依赖于之前的其他框, 比如作者/热门文章之类的)

**Comment by adlered** [comment]
你好，这个情况是由于你的浏览器宽度不足哦，建议你使用以下步骤尝试：
1. 在绿化设定中将显示方式调整为`平铺模式`
2. 在CSDN中调整浏览器的缩放为 90% 或更小（取决于目录刚好可以显示的大小）
