### ISSUE TITLE
跪求也搞个简书

### ISSUE THREAD

**Issue by ljyls** [adlered/CSDNGreener#85]
> 加入 QQ 群 1042370453 可直接与作者沟通

**Comment by adlered** [comment]
收到，后续开发会考虑，感谢提议。

**Comment by CHN-STUDENT** [comment]
+1 简书那个也可以屏蔽一下，也是广告和二维码影响体验！
好好学技术，干什么非被割韭菜。
感谢作者大大的付出！

**Comment by licoba** [comment]
+1 一人打字，求更新简书版本

**Comment by adlered** [comment]
JianShuGreener已推出，欢迎试用：https://greasyfork.org/zh-CN/scripts/429640
目前为初代版本，欢迎提出意见
