### ISSUE TITLE
图片混文字时，无法完整复制，图片不会被复制下来

### ISSUE THREAD

**Issue by blackcatIan** [adlered/CSDNGreener#87]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
环境：WIN10，chrome88（有脚本），firefox86(干净无脚本插件)
**预期结果：**
已安装脚本的浏览器，图片文字可以一并复制下来
**实际结果：**
1.复制CSDN整片文章时，当文字中有多张图片，文字和图片穿插的文本情况时，_**复制下来后只有文本。图片不会被复制下来**_
2.当只复制短小的文本+只包含1张图片作为结束的情况，可以被复制，文字和图片皆有。
3.点选单张图片右击复制，单个图片可以被复制。
以上现象无论是安装有脚本的chrome（脚本已运行）又或者是无脚本的firefox都会发生。
测试用例参考文章：https://blog.csdn.net/qq_39949963/article/details/79362501

希望能解决，让大家好好方便摘抄知识笔记。

**Comment by adlered** [comment]
感谢你的细致反馈，下个版本会重构CSDN的文章渲染，尽量修复此问题。

**Comment by WVVxm** [comment]
> 感谢你的细致反馈，下个版本会重构CSDN的文章渲染，尽量修复此问题。

加这行可以移除 oncopy　的监听，　之后就能和协复制了

` let el = $("main .blog-content-box")[0];
            let elClone = el.cloneNode(true);
            el.parentNode.replaceChild(elClone, el);`
