### ISSUE TITLE
手机版适配问题

### ISSUE THREAD

**Issue by Alan996** [adlered/CSDNGreener#89]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
![Screenshot_2021-03-21-20-41-59-516_org mozilla firefox](https://user-images.githubusercontent.com/41531958/111905353-2a9b3e80-8a86-11eb-9a97-d4fc11fd4556.jpg)
希望能尽快适配手机版。目前排版体验很不好。本人愚昧，想不出怎么样排版。firefox手机版最后支持tampermonkey Version: 68.11.0

**Comment by Alan996** [comment]
![Screenshot_2021-03-22-12-18-08-454_org mozilla firefox](https://user-images.githubusercontent.com/41531958/111940034-b81f7280-8b08-11eb-965d-eec4b527cb10.jpg)

**Comment by Alan996** [comment]
![Screenshot_2021-03-22-12-19-31-633_org mozilla firefox](https://user-images.githubusercontent.com/41531958/111940097-e2713000-8b08-11eb-8433-efe6e2e200f4.jpg)

**Comment by adlered** [comment]
收到，使用的浏览器是？
