### ISSUE TITLE
我感觉更新了有问题

### ISSUE THREAD

**Issue by nanxiangqingfeng** [adlered/CSDNGreener#94]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
使用插件后,页面不停地抖动,有时很微弱,有时很激烈 我的设备是 Mac  浏览器是 Chrome 版本 90.0.4430.85（正式版本） (x86_64)

**Comment by adlered** [comment]
请检查是否有其它插件冲突呢
