### ISSUE TITLE
好像脚本失效了？

### ISSUE THREAD

**Issue by DearDeer7** [adlered/CSDNGreener#95]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
最近两天使用CSDN，**插件不起效了**
![image](https://user-images.githubusercontent.com/42965045/116514606-d9406380-a8fd-11eb-8ff3-9e7e9e0ce440.png)

**Comment by adlered** [comment]
检查下是否有插件冲突呢

**Comment by DearDeer7** [comment]
> 检查下是否有插件
检查了下，还真是，貌似和一个网盘智能识别助手冲突了，关掉就好使了，感谢
![image](https://user-images.githubusercontent.com/42965045/116662701-af07a800-a9c8-11eb-9942-fa5dc3e923d8.png)
