### ISSUE TITLE
csdn脚本顶部闪烁，出现bug，影响使用

### ISSUE THREAD

**Issue by lyjhyjyes** [adlered/CSDNGreener#98]
> 加入 QQ 群 1042370453 可直接与作者沟通

### 请描述你遇到的问题：
csdn脚本顶部闪烁，出现bug，影响使用
https://greasyfork.org/zh-CN/scripts/378351
win10 chrome 版本 90.0.4430.85（正式版本） （64 位），油猴4.13版本
顶部横幅不断闪烁，影响使用
不好意思，不太会使用图床，一共2张图片，其余用来做对比，测试
[url=http://skuimg.com/x/?i=i/2021/07/19/9ddvl5k.png][img]http://skuimg.com/i/2021/07/19/9ddvl5k.png[/img][/url]
[url=http://skuimg.com/x/?i=i/2021/07/19/xqlapy.png][img]http://skuimg.com/i/2021/07/19/xqlapy.png[/img][/url]
http://skuimg.com/i/2021/07/19/9ddvl5k.png
http://skuimg.com/i/2021/07/19/xqlapy.png
![](http://skuimg.com/i/2021/07/19/9ddvl5k.png)
![](http://skuimg.com/i/2021/07/19/xqlapy.png)
<img src="http://skuimg.com/i/2021/07/19/9ddvl5k.png" />
<img src="http://skuimg.com/i/2021/07/19/xqlapy.png" />

**Comment by adlered** [comment]
收到，我目前使用：
油猴 v4.13
Chrome 91.0.4472.114（正式版本） (arm64)
macOS 11.4
进行测试并没有遇到闪烁的问题。
可否上传动图？
是否每个博客页面都会闪烁？
尝试关闭`向下滚动自动隐藏顶栏`功能试试看
