### ISSUE TITLE
自动隐藏底栏特性修改（期望）

### ISSUE THREAD

**Issue by RuoMengAwA** [adlered/CSDNGreener#99]
### 请描述你遇到的问题：
使用浏览器：edge浏览器
系统：win10
脚本使用：仅测试使用该脚本
***
在滚动状态下，下侧交互栏无隐藏，结束鼠标交互后，隐藏时间较长
![image](https://user-images.githubusercontent.com/73015949/129869234-b62a71eb-dfb3-4d0b-9071-5c8c4b5b4347.png)
![image](https://user-images.githubusercontent.com/73015949/129869241-29f636e9-ccb0-4cbf-8f22-68708a886922.png)
结束鼠标滚动后仍然保持，需过3s才会自动隐藏
***
### 期望
期望作者可否将下侧交互栏完全隐藏，在放大网页浏览博客时非常好用
谢谢啦
（已点小星星（笑））

**Comment by adlered** [comment]
Related `58b92c3` `bbd666f`

**Comment by adlered** [comment]
Related #58b92c3 #bbd666f

**Comment by adlered** [comment]
Related 58b92c3 bbd666f
